export default {
  id: 3,
  name: 'Offset Approach',
  description: 'Offset landing pad with a crossing fuel lane.',
  gravity: -4.2,
  thrustPower: 7.35,
  steeringPower: 3.9,
  damping: 0.99,
  windStrength: 0,
  windDirection: { x: 0, y: 0, z: 0 },
  maxSpeed: { horizontal: 6.4, verticalUp: 7.1, verticalDown: 8.8 },
  fuelBurnRate: 10.2,
  launchPad: { position: { x: -8, y: 0.1, z: 48 }, size: { x: 5.2, y: 0.2, z: 5.2 } },
  landingPad: { position: { x: 10, y: 0.1, z: -86 }, size: { x: 5.1, y: 0.2, z: 5.1 } },
  landingThresholds: { verticalSpeed: 2.05, horizontalSpeed: 1.85, angle: 0.42 },
  worldBounds: { minX: -26, maxX: 26, minZ: -104, maxZ: 56, maxY: 30 },
  terrain: { width: 60, depth: 176, segments: 68, amplitude: 1.25, frequency: 0.15, seed: 17 },
  obstacles: [],
  pickups: [
    { id: 301, type: 'instant', amount: 18, position: { x: -5, y: 4.8, z: 22 }, radius: 1.1 },
    { id: 302, type: 'instant', amount: 18, position: { x: -1, y: 5.7, z: -8 }, radius: 1.1 },
    { id: 303, type: 'instant', amount: 20, position: { x: 4, y: 5.1, z: -40 }, radius: 1.1 },
    { id: 304, type: 'instant', amount: 24, position: { x: 8, y: 4.2, z: -66 }, radius: 1.1 }
  ],
  roofs: [],
  walls: [],
  tutorialMessages: ['The landing pad is offset to the right.', 'Steer through each droplet in small taps.', 'Line up early for the offset landing pad.'],
  scoreMultiplier: 1.25,
  visualTheme: { terrain: 0x202a32 }
};
