export default {
  id: 2,
  name: 'Long Hop',
  description: 'Longer route with gentle hills and staggered fuel droplets.',
  gravity: -4.05,
  thrustPower: 7.25,
  steeringPower: 3.7,
  damping: 0.991,
  windStrength: 0,
  windDirection: { x: 0, y: 0, z: 0 },
  maxSpeed: { horizontal: 6.2, verticalUp: 7, verticalDown: 8.4 },
  fuelBurnRate: 9.8,
  launchPad: { position: { x: -3, y: 0.1, z: 44 }, size: { x: 5.5, y: 0.2, z: 5.5 } },
  landingPad: { position: { x: 5, y: 0.1, z: -76 }, size: { x: 5.8, y: 0.2, z: 5.8 } },
  landingThresholds: { verticalSpeed: 2.2, horizontalSpeed: 2, angle: 0.46 },
  worldBounds: { minX: -24, maxX: 24, minZ: -94, maxZ: 52, maxY: 30 },
  terrain: { width: 56, depth: 160, segments: 64, amplitude: 1.0, frequency: 0.13, seed: 9 },
  obstacles: [],
  pickups: [
    { id: 201, type: 'instant', amount: 18, position: { x: -1.5, y: 4.4, z: 18 }, radius: 1.1 },
    { id: 202, type: 'instant', amount: 18, position: { x: 2, y: 5.3, z: -8 }, radius: 1.1 },
    { id: 203, type: 'instant', amount: 20, position: { x: 4.2, y: 4.7, z: -36 }, radius: 1.1 },
    { id: 204, type: 'instant', amount: 22, position: { x: 5, y: 4.0, z: -58 }, radius: 1.1 }
  ],
  roofs: [],
  walls: [],
  tutorialMessages: ['Follow the fuel line over the longer hop.', 'Use small steering corrections.', 'Slow down before the final descent.'],
  scoreMultiplier: 1.12,
  visualTheme: { terrain: 0x222b35 }
};
